export const catalogCategories = [
  { id: "all", label: "Вся подборка" },
  { id: "volleyball", label: "Волейбол" },
  { id: "training", label: "Тренировки" },
  { id: "recovery", label: "Восстановление" },
  { id: "lifestyle", label: "Лайфстайл" },
  { id: "apparel", label: "Одежда и аксессуары" },
] as const

export type CatalogCategory = Exclude<
  (typeof catalogCategories)[number]["id"],
  "all"
>

export type ProductKind = "footwear" | "apparel" | "accessory"

export const MARKET_PRICE_BASIS =
  "Редакционный ориентир · выборка РФ 26.07.2026"

export interface CatalogProduct {
  slug: string
  brand: string
  name: string
  category: CatalogCategory
  categoryLabel: string
  kind: ProductKind
  sportPriority: boolean
  query: string
  note: string
  marketPrice?: string
  priceBasis?: string
  image: string
}

const sportProducts: readonly Omit<CatalogProduct, "image">[] = [
  {
    slug: "asics-sky-elite-ff-3",
    brand: "ASICS",
    name: "SKY ELITE FF 3",
    category: "volleyball",
    categoryLabel: "Волейбол · прыжок",
    kind: "footwear",
    sportPriority: true,
    query: "ASICS SKY ELITE FF 3 volleyball",
    note: "Флагманский low · для атакующих игроков",
    marketPrice: "17,5–20,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "asics-sky-elite-ff-mt-3",
    brand: "ASICS",
    name: "SKY ELITE FF MT 3",
    category: "volleyball",
    categoryLabel: "Волейбол · mid",
    kind: "footwear",
    sportPriority: true,
    query: "ASICS SKY ELITE FF MT 3 volleyball",
    note: "Средняя высота · прыжок и фиксация",
    marketPrice: "20–22,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "asics-metarise-2",
    brand: "ASICS",
    name: "METARISE 2",
    category: "volleyball",
    categoryLabel: "Волейбол · премиум",
    kind: "footwear",
    sportPriority: true,
    query: "ASICS METARISE 2 1051A089 volleyball",
    note: "Премиальная модель · приоритет для доигровщика",
    marketPrice: "24–34 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "asics-netburner-ballistic-ff-4",
    brand: "ASICS",
    name: "NETBURNER BALLISTIC FF 4",
    category: "volleyball",
    categoryLabel: "Волейбол · стабильность",
    kind: "footwear",
    sportPriority: true,
    query: "ASICS NETBURNER BALLISTIC FF 4 volleyball",
    note: "Быстрые перемещения · боковая устойчивость",
    marketPrice: "10,5–17,6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "asics-gel-tactic-13",
    brand: "ASICS",
    name: "GEL-TACTIC 13",
    category: "volleyball",
    categoryLabel: "Волейбол · универсальная",
    kind: "footwear",
    sportPriority: true,
    query: "ASICS GEL-TACTIC 13 volleyball",
    note: "Универсальный зал · средний ценовой сегмент",
    marketPrice: "14–16 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-lightning-z8",
    brand: "Mizuno",
    name: "WAVE LIGHTNING Z8",
    category: "volleyball",
    categoryLabel: "Волейбол · скорость",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE LIGHTNING Z8 volleyball",
    note: "Лёгкий low · быстрый разбег и смена направления",
    marketPrice: "12,5–15,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-lightning-z8-mid",
    brand: "Mizuno",
    name: "WAVE LIGHTNING Z8 MID",
    category: "volleyball",
    categoryLabel: "Волейбол · mid",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE LIGHTNING Z8 MID volleyball",
    note: "Скорость low-линейки · более высокая посадка",
    marketPrice: "13,3–19 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-momentum-elite-mid",
    brand: "Mizuno",
    name: "WAVE MOMENTUM ELITE MID",
    category: "volleyball",
    categoryLabel: "Волейбол · амортизация",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE MOMENTUM ELITE MID volleyball",
    note: "Амортизация приземлений · средняя высота",
    marketPrice: "15,5–18 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-momentum-pro",
    brand: "Mizuno",
    name: "WAVE MOMENTUM PRO",
    category: "volleyball",
    categoryLabel: "Волейбол · баланс",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE MOMENTUM PRO volleyball",
    note: "Комфорт и устойчивость · средний сегмент",
    marketPrice: "11,5–13,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-luminous-3",
    brand: "Mizuno",
    name: "WAVE LUMINOUS 3",
    category: "volleyball",
    categoryLabel: "Волейбол · универсальная",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE LUMINOUS 3 volleyball",
    note: "Универсальная амортизация · тренировки и игры",
    marketPrice: "12,7–15 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-wave-voltage-2",
    brand: "Mizuno",
    name: "WAVE VOLTAGE 2",
    category: "volleyball",
    categoryLabel: "Волейбол · доступная",
    kind: "footwear",
    sportPriority: true,
    query: "Mizuno WAVE VOLTAGE 2 volleyball",
    note: "Доступный вход · любительские тренировки",
    marketPrice: "9–13 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-zoom-hyperset-2",
    brand: "Nike",
    name: "ZOOM HYPERSET 2",
    category: "volleyball",
    categoryLabel: "Волейбол · премиум",
    kind: "footwear",
    sportPriority: true,
    query: "Nike ZOOM HYPERSET 2 volleyball",
    note: "Импортная модель · верхний ценовой сегмент",
    marketPrice: "24–25 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-hyperace-3-se",
    brand: "Nike",
    name: "HYPERACE 3 SE",
    category: "volleyball",
    categoryLabel: "Волейбол · универсальная",
    kind: "footwear",
    sportPriority: true,
    query: "Nike HYPERACE 3 SE volleyball",
    note: "Универсальная линия · размер обязательно сверить",
    marketPrice: "18,9–21 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "adidas-crazyflight-6-mid",
    brand: "adidas",
    name: "CRAZYFLIGHT 6 / MID",
    category: "volleyball",
    categoryLabel: "Волейбол · импорт",
    kind: "footwear",
    sportPriority: true,
    query: "adidas CRAZYFLIGHT 6 MID volleyball",
    note: "Тестовый импортный слот · low или mid",
    marketPrice: "16–25 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-metcon-10",
    brand: "Nike",
    name: "METCON 10",
    category: "training",
    categoryLabel: "Тренировки · силовые",
    kind: "footwear",
    sportPriority: true,
    query: "Nike METCON 10 training",
    note: "Силовой зал · устойчивая платформа",
    marketPrice: "21–24 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "reebok-nano-x5",
    brand: "Reebok",
    name: "NANO X5",
    category: "training",
    categoryLabel: "Тренировки · функциональные",
    kind: "footwear",
    sportPriority: true,
    query: "Reebok NANO X5 training",
    note: "Функциональный тренинг · широкий сценарий",
    marketPrice: "10–13,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "adidas-dropset-3",
    brand: "adidas",
    name: "DROPSET 3",
    category: "training",
    categoryLabel: "Тренировки · зал",
    kind: "footwear",
    sportPriority: true,
    query: "adidas DROPSET 3 training",
    note: "Силовые упражнения · стабильность в зале",
    marketPrice: "13–16 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "under-armour-tribase-reign-6",
    brand: "Under Armour",
    name: "TRIBASE REIGN 6",
    category: "training",
    categoryLabel: "Тренировки · стабильность",
    kind: "footwear",
    sportPriority: true,
    query: "Under Armour TRIBASE REIGN 6 training",
    note: "Устойчивая база · работа с нагрузкой",
    marketPrice: "10–12,5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "hoka-ora-recovery-slide-3",
    brand: "HOKA",
    name: "ORA RECOVERY SLIDE 3",
    category: "recovery",
    categoryLabel: "Восстановление · слайды",
    kind: "footwear",
    sportPriority: true,
    query: "HOKA ORA RECOVERY SLIDE 3",
    note: "После тренировки · мягкий recovery-сценарий",
    marketPrice: "5,5–7,7 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-calm-slide",
    brand: "Nike",
    name: "CALM SLIDE",
    category: "recovery",
    categoryLabel: "Восстановление · слайды",
    kind: "footwear",
    sportPriority: true,
    query: "Nike CALM SLIDE",
    note: "Массовый recovery-сегмент · размер сверить",
    marketPrice: "3,8–7,7 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-dri-fit-volleyball-jersey",
    brand: "Nike",
    name: "Dri-FIT Volleyball Jersey",
    category: "volleyball",
    categoryLabel: "Волейбол · джерси",
    kind: "apparel",
    sportPriority: true,
    query: "Nike Dri-FIT volleyball jersey blue",
    note: "Игровой верх · точный состав сверить",
    marketPrice: "2,1–4,6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "mizuno-volleyball-practice-tee",
    brand: "Mizuno",
    name: "Volleyball Practice Tee",
    category: "volleyball",
    categoryLabel: "Волейбол · футболка",
    kind: "apparel",
    sportPriority: true,
    query: "Mizuno volleyball practice tee",
    note: "Тренировочная футболка · свободное движение",
    marketPrice: "2,1–4,6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "asics-actibreeze-match-top",
    brand: "ASICS",
    name: "ACTIBREEZE Match Top",
    category: "volleyball",
    categoryLabel: "Волейбол · пляж",
    kind: "apparel",
    sportPriority: true,
    query: "ASICS ACTIBREEZE match sleeveless top",
    note: "Лёгкий верх · пляжные и жаркие тренировки",
    marketPrice: "3–6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "adidas-crazyflight-shorts",
    brand: "adidas",
    name: "Crazyflight Match Shorts",
    category: "volleyball",
    categoryLabel: "Волейбол · шорты",
    kind: "apparel",
    sportPriority: true,
    query: "adidas volleyball match shorts",
    note: "Игровые шорты · длину и посадку сверить",
    marketPrice: "1,7–2,6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-pro-compression-shorts",
    brand: "Nike",
    name: "Pro Compression Shorts",
    category: "training",
    categoryLabel: "Тренировки · компрессия",
    kind: "apparel",
    sportPriority: true,
    query: "Nike Pro compression shorts men",
    note: "Базовый слой · под игровые шорты",
    marketPrice: "2,5–5 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "under-armour-heatgear-top",
    brand: "Under Armour",
    name: "HeatGear Compression Top",
    category: "training",
    categoryLabel: "Тренировки · лонгслив",
    kind: "apparel",
    sportPriority: true,
    query: "Under Armour HeatGear compression long sleeve men",
    note: "Компрессионный лонгслив · базовый слой",
    marketPrice: "3,5–7,2 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "adidas-own-the-run-shorts",
    brand: "adidas",
    name: "Own The Run Shorts",
    category: "training",
    categoryLabel: "Тренировки · шорты",
    kind: "apparel",
    sportPriority: true,
    query: "adidas Own The Run shorts men",
    note: "Бег и ОФП · лёгкая ткань",
    marketPrice: "3–6 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "on-performance-tights",
    brand: "On",
    name: "Performance Tights",
    category: "training",
    categoryLabel: "Тренировки · тайтсы",
    kind: "apparel",
    sportPriority: true,
    query: "On Performance Tights men",
    note: "ОФП и прохладная погода · тайтсы",
    marketPrice: "6–10 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "nike-therma-fit-training-hoodie",
    brand: "Nike",
    name: "Therma-FIT Training Hoodie",
    category: "recovery",
    categoryLabel: "Восстановление · худи",
    kind: "apparel",
    sportPriority: true,
    query: "Nike Therma-FIT training hoodie men",
    note: "Разминка и дорога после тренировки",
    marketPrice: "4–8 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
  {
    slug: "adidas-zne-track-jacket",
    brand: "adidas",
    name: "Z.N.E. Track Jacket",
    category: "recovery",
    categoryLabel: "Восстановление · олимпийка",
    kind: "apparel",
    sportPriority: true,
    query: "adidas Z.N.E. full zip track jacket men",
    note: "Разминка, дорога и восстановление",
    marketPrice: "8–14 тыс. ₽",
    priceBasis: MARKET_PRICE_BASIS,
  },
] as const

const existingProducts: readonly Omit<CatalogProduct, "image">[] = [
  {
    slug: "asics-gel-1130-black-pure-silver",
    brand: "ASICS",
    name: "GEL-1130 Black / Pure Silver",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "ASICS GEL-1130 Black Pure Silver 1201A906-001",
    note: "Ретро-раннер · серебристые детали",
  },
  {
    slug: "asics-gel-nyc-cream-oyster-grey",
    brand: "ASICS",
    name: "GEL-NYC Cream / Oyster Grey",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "ASICS GEL-NYC Cream Oyster Grey 1201A789-103",
    note: "Многослойный верх · нейтральная палитра",
  },
  {
    slug: "asics-gel-kayano-14-white-midnight",
    brand: "ASICS",
    name: "GEL-KAYANO 14 White / Midnight",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "ASICS GEL-KAYANO 14 White Midnight 1202A056-109",
    note: "Технологичный силуэт · сетка и металл",
  },
  {
    slug: "salomon-xt-6-white-lunar-rock",
    brand: "Salomon",
    name: "XT-6 White / Lunar Rock",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Salomon XT-6 White Lunar Rock L41252900",
    note: "Трейловый силуэт · городская пара",
  },
  {
    slug: "new-balance-9060-rain-cloud",
    brand: "New Balance",
    name: "9060 Rain Cloud",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "New Balance 9060 Rain Cloud U9060GRY",
    note: "Объёмная подошва · серый монохром",
  },
  {
    slug: "new-balance-2002r-protection-pack",
    brand: "New Balance",
    name: "2002R Protection Pack Rain Cloud",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "New Balance 2002R Protection Pack Rain Cloud M2002RDA",
    note: "Необработанные края · сложная фактура",
  },
  {
    slug: "new-balance-530-white-silver-navy",
    brand: "New Balance",
    name: "530 White / Silver / Navy",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "New Balance 530 White Silver Navy MR530SG",
    note: "Лёгкий ретро-раннер · на каждый день",
  },
  {
    slug: "new-balance-1906r-silver-metallic",
    brand: "New Balance",
    name: "1906R Silver Metallic",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "New Balance 1906R Silver Metallic M1906RER",
    note: "Сетчатый верх · техничные накладки",
  },
  {
    slug: "nike-zoom-vomero-5-photon-dust",
    brand: "Nike",
    name: "Zoom Vomero 5 Photon Dust",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Nike Zoom Vomero 5 Photon Dust HF7723-001",
    note: "Слоистая конструкция · мягкая амортизация",
  },
  {
    slug: "nike-air-max-95-black-anthracite",
    brand: "Nike SB",
    name: "Air Max 95 Black / Anthracite",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Nike SB Air Max 95 Black Anthracite HF7545-002",
    note: "Культовый градиент · тёмная расцветка",
  },
  {
    slug: "nike-air-force-1-07-white",
    brand: "Nike",
    name: "Air Force 1 ’07 White",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Nike Air Force 1 07 White CW2288-111",
    note: "Белая кожа · базовый силуэт",
  },
  {
    slug: "nike-dunk-low-panda",
    brand: "Nike",
    name: "Dunk Low Retro White / Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Nike Dunk Low Retro White Black Panda DD1391-100",
    note: "Контрастная классика · расцветка Panda",
  },
  {
    slug: "air-jordan-4-black-cat",
    brand: "Jordan",
    name: "Air Jordan 4 Retro Black Cat",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Air Jordan 4 Retro Black Cat FV5029-010",
    note: "Чёрный монохром · баскетбольная классика",
  },
  {
    slug: "air-jordan-5-wolf-grey",
    brand: "Jordan",
    name: "Air Jordan 5 Retro Wolf Grey",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Air Jordan 5 Retro Wolf Grey DD0587-002",
    note: "Серый нубук · прозрачные детали",
  },
  {
    slug: "air-jordan-1-low-white-black",
    brand: "Jordan",
    name: "Air Jordan 1 Low White / Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кроссовки",
    kind: "footwear",
    sportPriority: false,
    query: "Air Jordan 1 Low White Black 553558-132",
    note: "Низкий профиль · универсальный контраст",
  },
  {
    slug: "adidas-samba-og-white-black",
    brand: "adidas",
    name: "Samba OG White / Core Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кеды",
    kind: "footwear",
    sportPriority: false,
    query: "adidas Samba OG White Core Black B75806",
    note: "Кожаный верх · каучуковая подошва",
  },
  {
    slug: "adidas-gazelle-indoor-green",
    brand: "adidas",
    name: "Gazelle Indoor Collegiate Green",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кеды",
    kind: "footwear",
    sportPriority: false,
    query: "adidas Gazelle Indoor Collegiate Green JI2062",
    note: "Замша · насыщенный зелёный",
  },
  {
    slug: "adidas-campus-00s-core-black",
    brand: "adidas",
    name: "Campus 00s Core Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кеды",
    kind: "footwear",
    sportPriority: false,
    query: "adidas Campus 00s Core Black HQ8708",
    note: "Объёмный язык · эстетика нулевых",
  },
  {
    slug: "converse-chuck-70-high-black",
    brand: "Converse",
    name: "Chuck 70 High Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кеды",
    kind: "footwear",
    sportPriority: false,
    query: "Converse Chuck 70 High Black 162050C",
    note: "Плотный канвас · высокая посадка",
  },
  {
    slug: "vans-old-skool-36-black-white",
    brand: "Vans",
    name: "Old Skool Black / White",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · кеды",
    kind: "footwear",
    sportPriority: false,
    query: "Vans Old Skool Black White VN000D3HY28",
    note: "Замша и канвас · скейт-классика",
  },
  {
    slug: "nike-mind-001-slide-black",
    brand: "Nike",
    name: "Mind 001 × Fragment Black",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · слайды",
    kind: "footwear",
    sportPriority: false,
    query: "Nike Mind 001 Fragment Black IQ8502-001",
    note: "Минималистичный слайд · фактурная стелька",
  },
  {
    slug: "timberland-field-boot-beef-broccoli",
    brand: "Timberland",
    name: "Waterproof Field Boot Beef & Broccoli",
    category: "lifestyle",
    categoryLabel: "Лайфстайл · ботинки",
    kind: "footwear",
    sportPriority: false,
    query: "Timberland Waterproof Field Boot Beef and Broccoli",
    note: "Водостойкая кожа · outdoor-силуэт",
  },
  {
    slug: "essentials-hoodie-light-oatmeal",
    brand: "Fear of God Essentials",
    name: "Hoodie Light Oatmeal",
    category: "apparel",
    categoryLabel: "Одежда · худи",
    kind: "apparel",
    sportPriority: false,
    query: "Fear of God Essentials Hoodie Light Oatmeal",
    note: "Свободный крой · базовый оттенок",
  },
  {
    slug: "north-face-1996-nuptse-black",
    brand: "The North Face",
    name: "1996 Retro Nuptse Black",
    category: "apparel",
    categoryLabel: "Одежда · куртка",
    kind: "apparel",
    sportPriority: false,
    query: "The North Face 1996 Retro Nuptse Jacket Black NF0A3C8D",
    note: "Пуховая куртка · городской объём",
  },
  {
    slug: "supreme-mm6-zip-hoodie-black",
    brand: "Supreme × MM6",
    name: "Box Logo Zip Hoodie Black",
    category: "apparel",
    categoryLabel: "Одежда · zip-худи",
    kind: "apparel",
    sportPriority: false,
    query: "Supreme MM6 Maison Margiela Box Logo Zip Up Hoodie Black",
    note: "Коллаборация · zip-худи",
  },
  {
    slug: "jordan-nigel-sylvester-bike-air-jersey",
    brand: "Jordan × Nigel Sylvester",
    name: "Bike Air Jersey",
    category: "apparel",
    categoryLabel: "Одежда · джерси",
    kind: "apparel",
    sportPriority: false,
    query: "Jordan Nigel Sylvester Bike Air Jersey",
    note: "Спортивная графика · свободный силуэт",
  },
  {
    slug: "nike-barcelona-ronaldinho-jersey",
    brand: "Nike Football",
    name: "FC Barcelona Ronaldinho #10 Jersey",
    category: "apparel",
    categoryLabel: "Одежда · джерси",
    kind: "apparel",
    sportPriority: false,
    query: "Nike FC Barcelona Ronaldinho number 10 Jersey",
    note: "Футбольная классика · номер 10",
  },
  {
    slug: "kith-adidas-messi-tee",
    brand: "Kith × adidas Football",
    name: "Lionel Messi Graphic Tee",
    category: "apparel",
    categoryLabel: "Одежда · футболка",
    kind: "apparel",
    sportPriority: false,
    query: "Kith adidas Football Lionel Messi Graphic Tee ADKU4264",
    note: "Футбольная коллекция · графический принт",
  },
  {
    slug: "nike-hoops-elite-backpack",
    brand: "Nike",
    name: "Hoops Elite Backpack Black",
    category: "apparel",
    categoryLabel: "Аксессуары · рюкзак",
    kind: "accessory",
    sportPriority: false,
    query: "Nike Hoops Elite Backpack Black Anthracite Metallic Silver DX9786-010",
    note: "Вместительный рюкзак · спортивные отделения",
  },
  {
    slug: "new-era-yankees-59fifty-black",
    brand: "New Era",
    name: "New York Yankees 59FIFTY Black",
    category: "apparel",
    categoryLabel: "Аксессуары · кепка",
    kind: "accessory",
    sportPriority: false,
    query: "New Era New York Yankees 59FIFTY Black 60955984",
    note: "Фиксированная посадка · чёрный цвет",
  },
] as const

const catalogProductSource = [...sportProducts, ...existingProducts] as const

export const catalogProducts: readonly CatalogProduct[] =
  catalogProductSource.map((product) => ({
    ...product,
    image: `catalog/${product.slug}.webp`,
  }))

export function filterCatalog(
  products: readonly CatalogProduct[],
  category: "all" | CatalogCategory,
  search: string,
): CatalogProduct[] {
  const normalizedSearch = search.trim().toLocaleLowerCase("ru")

  return products.filter((product) => {
    if (category !== "all" && product.category !== category) return false
    if (!normalizedSearch) return true

    return [
      product.brand,
      product.name,
      product.query,
      product.categoryLabel,
      product.kind,
      product.note,
      product.marketPrice ?? "",
    ]
      .join(" ")
      .toLocaleLowerCase("ru")
      .includes(normalizedSearch)
  })
}
