"""Build deterministic card-sized catalogue thumbnails from active unified media."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
UNIFIED_MANIFEST = ROOT / "catalog-media" / "unified-catalog-media.json"
OUTPUT_DIR = ROOT / "public" / "catalog" / "thumbs"
RUNTIME_MANIFEST = ROOT / "src" / "catalog" / "card-thumbnail-versions.ts"
WIDTHS = (640, 960, 1280)
ASPECT_RATIO = 4 / 3
CARD_POSITIONS = (1, 2, 3)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_runtime_manifest(entries: list[dict[str, object]]) -> None:
    versions = {
        f"{entry['slug']}-{entry['position']}-{entry['width']}": str(entry["sha256"])[:16]
        for entry in entries
    }
    lines = [
        "/* Generated by scripts/build_catalog_card_thumbnails.py. Do not edit manually. */",
        "",
        "const thumbnailVersions: Record<string, string> = {",
    ]
    for key, version in sorted(versions.items()):
        lines.append(f'  "{key}": "{version}",')
    lines.extend(
        [
            "}",
            "",
            "export function getCardThumbnailUrl(slug: string, position: number, width: number): string {",
            "  const file = `catalog/thumbs/${slug}-${position}-${width}.webp`",
            "  const version = thumbnailVersions[`${slug}-${position}-${width}`]",
            "  return version ? `${file}?v=${version}` : file",
            "}",
            "",
        ]
    )
    RUNTIME_MANIFEST.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    manifest = json.loads(UNIFIED_MANIFEST.read_text(encoding="utf-8"))
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # This directory is generator-owned. Remove old responsive variants so the
    # manifest and runtime srcset cannot silently retain stale thumbnails.
    for stale in OUTPUT_DIR.glob("*.webp"):
        stale.unlink()
    entries: list[dict[str, object]] = []

    for product in manifest["products"]:
        slug = product["slug"]
        frames = {frame["position"]: frame for frame in product["frames"]}
        # ProductCard uses frame 3 for footwear and frame 2 for other product
        # kinds. The unified manifest deliberately contains only media metadata,
        # so emit both hover candidates rather than infer a product kind here.
        for position in CARD_POSITIONS:
            frame = frames[position]
            source = ROOT / frame["file"]
            with Image.open(source) as image:
                rgb = image.convert("RGB")
                for width in WIDTHS:
                    height = round(width / ASPECT_RATIO)
                    output = OUTPUT_DIR / f"{slug}-{position}-{width}.webp"
                    rendered = rgb.resize((width, height), Image.Resampling.LANCZOS)
                    rendered.save(output, format="WEBP", quality=72, method=6)
                    entries.append(
                        {
                            "slug": slug,
                            "position": position,
                            "source": frame["file"],
                            "source_sha256": sha256(source),
                            "file": f"public/catalog/thumbs/{output.name}",
                            "sha256": sha256(output),
                            "width": width,
                            "height": height,
                        }
                    )

    payload = {
        "schema_version": 1,
        "generator": "scripts/build_catalog_card_thumbnails.py",
        "widths": list(WIDTHS),
        "aspect_ratio": "4:3",
        "entries": sorted(entries, key=lambda entry: (str(entry["slug"]), int(entry["position"]))),
    }
    (OUTPUT_DIR / "manifest.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    write_runtime_manifest(entries)
    print(f"Built {len(entries)} responsive card thumbnails at {', '.join(map(str, WIDTHS))}px wide")


if __name__ == "__main__":
    main()
